### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by JungSungHo** [JungSungHo/VUE-TUTORIAL2#1]
### How to Configure Vue.Js
  - https://github.com/JungSungHo/VUE-TUTORIAL2/wiki/Vue.Js-Setting-Manual

### Task
  - [ ] Configuration / Installation 
  - [ ] Running Unit Test ([Unit Test Result](https://github.com/JungSungHo/VUE-TUTORIAL2/issues/1#issuecomment-1506155141) is All Clear)
  - [ ] Running e2e Test ([e2eTest Result](https://github.com/JungSungHo/VUE-TUTORIAL2/issues/1#issuecomment-1506162256) is All Clear)
  - [ ] Running lint check ([lint check Result](https://github.com/JungSungHo/VUE-TUTORIAL2/issues/1#issuecomment-1506166309) is No Errors)

### Related Link
  - https://sharkcoder.com/tools/vuejs
  - https://www.tutorialspoint.com/vuejs/index.htm
  - https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started

**Comment by JungSungHo** [comment]
## Unit Test Result

``` shell
$ npm run test:unit

> vue-tutorial2@0.1.0 test:unit
> vue-cli-service test:unit    

 PASS  tests/unit/example.spec.js (9.836 s)
  HelloWorld.vue
    √ renders props.msg when passed (39 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        24.179 s
Ran all test suites.
```

**Comment by JungSungHo** [comment]
## e2e Test Result
 - エラーの場合、コネクションの問題なのでコマンドを再実行する

```shell
$ npm run test:e2e

> vue-tutorial2@0.1.0 test:e2e
> vue-cli-service test:e2e

 INFO  Starting development server...


 DONE  Compiled successfully in 7369ms                                                                                                                                                          9:56:45


  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.36:8080/

  App is served in production mode.
  Note this is for preview or E2E testing only.

 INFO  Running end-to-end tests ...


[Test With Pageobjects] Test Suite
────────────────────────────────────────────────────────────────────
⠸ Starting ChromeDriver on port 9515...

ℹ Connected to ChromeDriver on port 9515 (1189ms).
  Using: chrome (112.0.5615.50) on WINDOWS.


  Running e2e tests using page objects:
───────────────────────────────────────────────────────────────────────────────────────────────────
  ℹ Loaded url http://localhost:8080/ in 502ms
  √ Element <#app> was visible after 34 milliseconds.
  √ Testing if element <img> has count: 1 (28ms)
  √ Expected element <Section [name=app],Element [name=@welcome]> to be visible (71ms)
  √ Expected element <Section [name=app],Element [name=@headline]> text to match: "/^Welcome to Your Vue\.js (.*)App$/" (44ms)

  ✨ PASSED. 4 assertions. (935ms)

  Running verify if string "e2e-nightwatch" is within the cli plugin links:
───────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Starting ChromeDriver on port 9515...


DevTools listening on ws://127.0.0.1:58133/devtools/browser/5634a24d-77c4-46b4-827a-aabcc3a6d52e
ℹ Connected to ChromeDriver on port 9515 (1067ms).
  Using: chrome (112.0.5615.50) on WINDOWS.

  ℹ Loaded url http://localhost:8080/ in 472ms
  √ Expected element <Section [name=app],Section [name=welcome],Element [name=@cliPluginLinks[0]]> text to contain: "e2e-nightwatch" (58ms)

  ✨ PASSED. 1 assertions. (1.667s)


[Test] Test Suite
──────────────────────────────────
⠸ Starting ChromeDriver on port 9515...

ℹ Connected to ChromeDriver on port 9515 (1197ms).
  Using: chrome (112.0.5615.50) on WINDOWS.


  Running default e2e tests:
───────────────────────────────────────────────────────────────────────────────────────────────────
  ℹ Loaded url http://localhost:8080/ in 503ms
  √ Element <#app> was visible after 53 milliseconds.
  √ Testing if element <.hello> is present (35ms)
DEPRECATED: the assertion .containsText() has been deprecated and will be removed from future versions. Use assert.textContains().
  √ Testing if element <h1> contains text 'Welcome to Your Vue.js App' (50ms)
  √ Testing if element <img> has count: 1 (39ms)

  ✨ PASSED. 4 assertions. (885ms)

  Running example e2e test using a custom command:
───────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Starting ChromeDriver on port 9515...


DevTools listening on ws://127.0.0.1:58179/devtools/browser/2b834d43-abf2-41b1-9dbd-e320698e4b6f
ℹ Connected to ChromeDriver on port 9515 (1145ms).
  Using: chrome (112.0.5615.50) on WINDOWS.

  ℹ Loaded url http://localhost:8080/ in 474ms
  √ Element <#app> was visible after 49 milliseconds.
  √ Passed [strictEqual]: 3 === 3
  √ Testing if element <.hello> is present (41ms)

  ✨ PASSED. 3 assertions. (1.943s)

  ✨ PASSED. 12 total assertions (9.037s)
 Wrote HTML report file to: C:\Users\NB-050\vue-tutorial2\tests\e2e\reports\nightwatch-html-report\index.html
```

**Comment by JungSungHo** [comment]
## Lint Check Result

```shell
NB-050@DESKTOP-IFVJ96L MINGW64 ~/vue-tutorial2 (master)
$ npm run lint

> vue-tutorial2@0.1.0 lint
> vue-cli-service lint

 DONE  No lint errors found!
```
